using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
namespace IoBuild.Api.Persistence;

[DbContext(typeof(IoBuildDbContext))]
[Migration("202608300004_DevicesTelemetry")]
public sealed class DevicesTelemetry : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(name: "devices", columns: table => new { Id = table.Column<int>(nullable: false).Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn), Name = table.Column<string>(maxLength: 200, nullable: false), Type = table.Column<string>(maxLength: 100, nullable: false), Location = table.Column<string>(maxLength: 500, nullable: false), MacAddress = table.Column<string>(maxLength: 17, nullable: true), ProjectId = table.Column<int>(nullable: false), UnitId = table.Column<int>(nullable: true), OwnerId = table.Column<int>(nullable: false), Source = table.Column<string>(maxLength: 30, nullable: true), Status = table.Column<string>(maxLength: 40, nullable: false) }, constraints: table => table.PrimaryKey("PK_devices", row => row.Id));
        migrationBuilder.CreateIndex("IX_devices_MacAddress", "devices", "MacAddress", unique: true); migrationBuilder.CreateIndex("IX_devices_ProjectId_UnitId_Type", "devices", new[] { "ProjectId", "UnitId", "Type" }, unique: true);
        migrationBuilder.CreateTable(name: "device_shadows", columns: table => new { DeviceId = table.Column<int>(nullable: false), DesiredJson = table.Column<string>(nullable: false), ReportedJson = table.Column<string>(nullable: true), ReportedAt = table.Column<DateTimeOffset>(nullable: false), ShadowVersion = table.Column<long>(nullable: false), UpdatedAt = table.Column<DateTimeOffset>(nullable: false) }, constraints: table => table.PrimaryKey("PK_device_shadows", row => row.DeviceId));
        migrationBuilder.CreateTable(name: "device_commands", columns: table => new { Id = table.Column<long>(nullable: false).Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn), DeviceId = table.Column<int>(nullable: false), CommandId = table.Column<string>(maxLength: 64, nullable: false), DesiredJson = table.Column<string>(nullable: false), IssuedAt = table.Column<DateTimeOffset>(nullable: false), PublishedAt = table.Column<DateTimeOffset>(nullable: true), PublishAttempts = table.Column<int>(nullable: false), AcknowledgedAt = table.Column<DateTimeOffset>(nullable: true) }, constraints: table => table.PrimaryKey("PK_device_commands", row => row.Id));
        migrationBuilder.CreateIndex("IX_device_commands_CommandId", "device_commands", "CommandId", unique: true); migrationBuilder.CreateIndex("IX_device_commands_DeviceId", "device_commands", "DeviceId");
        migrationBuilder.CreateTable(name: "device_telemetry", columns: table => new { Id = table.Column<long>(nullable: false).Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn), DeviceId = table.Column<int>(nullable: false), EventId = table.Column<string>(maxLength: 128, nullable: false), OccurredAt = table.Column<DateTimeOffset>(nullable: false), Status = table.Column<string>(maxLength: 40, nullable: false), ReportedJson = table.Column<string>(nullable: false), EnergyKwh = table.Column<double>(nullable: false), TemperatureC = table.Column<double>(nullable: false), VoltageV = table.Column<double>(nullable: false), InfluxWrittenAt = table.Column<DateTimeOffset>(nullable: true) }, constraints: table => table.PrimaryKey("PK_device_telemetry", row => row.Id));
        migrationBuilder.CreateIndex("IX_device_telemetry_EventId", "device_telemetry", "EventId", unique: true); migrationBuilder.CreateIndex("IX_device_telemetry_DeviceId_OccurredAt", "device_telemetry", new[] { "DeviceId", "OccurredAt" });
        migrationBuilder.CreateTable(name: "telemetry_recovery", columns: table => new { Id = table.Column<long>(nullable: false).Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn), EventId = table.Column<string>(maxLength: 128, nullable: false), CreatedAt = table.Column<DateTimeOffset>(nullable: false) }, constraints: table => table.PrimaryKey("PK_telemetry_recovery", row => row.Id)); migrationBuilder.CreateIndex("IX_telemetry_recovery_EventId", "telemetry_recovery", "EventId", unique: true); migrationBuilder.CreateTable(name: "unit_owner_projections", columns: table => new { UnitId = table.Column<int>(nullable: false), OwnerUserId = table.Column<int>(nullable: false), UpdatedAt = table.Column<DateTimeOffset>(nullable: false) }, constraints: table => table.PrimaryKey("PK_unit_owner_projections", row => row.UnitId)); migrationBuilder.CreateIndex("IX_unit_owner_projections_UnitId_OwnerUserId", "unit_owner_projections", new[] { "UnitId", "OwnerUserId" }, unique: true); migrationBuilder.CreateTable(name: "device_registry_tombstones", columns: table => new { DeviceId = table.Column<int>(nullable: false), CreatedAt = table.Column<DateTimeOffset>(nullable: false), PublishedAt = table.Column<DateTimeOffset>(nullable: true), PublishAttempts = table.Column<int>(nullable: false) }, constraints: table => table.PrimaryKey("PK_device_registry_tombstones", row => row.DeviceId));
    }
    protected override void Down(MigrationBuilder migrationBuilder) { migrationBuilder.DropTable("device_registry_tombstones"); migrationBuilder.DropTable("unit_owner_projections"); migrationBuilder.DropTable("telemetry_recovery"); migrationBuilder.DropTable("device_telemetry"); migrationBuilder.DropTable("device_commands"); migrationBuilder.DropTable("device_shadows"); migrationBuilder.DropTable("devices"); }
}
